version: '2'

services:
  web:
    volumes:
      - /data/spellingci-staging/tests:/myapp/_build/test/cover/
    networks:
      app_net:
        ipv4_address: 172.3.0.24

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.3.0.0/24
        gateway: 172.3.0.1
